name: test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Aerie UI Repo
        uses: actions/checkout@v3
      - name: Checkout Aerie Repo
        uses: actions/checkout@v3
        with:
          path: aerie
          repository: NASA-AMMOS/aerie
      - name: Start Aerie Services
        run: |
          docker compose -f docker-compose-test.yml up -d
          docker images
          docker ps -a
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Dependencies
        run: npx playwright install chromium --with-deps
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Playwright Test Results
          path: test-results
      - name: Print Logs for Aerie Services
        run: docker compose -f docker-compose-test.yml logs -t
      - name: Stop Aerie Services
        run: |
          docker compose -f docker-compose-test.yml down
          docker ps -a
